[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
goerli = "${SEPOLIA_RPC_URL}"

remappings=["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
